//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class Doanhthu : XPObject
    {
        DateTime fNgay;
        public DateTime Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<DateTime>(nameof(Ngay), ref fNgay, value); }
        }
        decimal fChira;
        public decimal Chira
        {
            get { return fChira; }
            set { SetPropertyValue<decimal>(nameof(Chira), ref fChira, value); }
        }
        decimal fThuvao;
        public decimal Thuvao
        {
            get { return fThuvao; }
            set { SetPropertyValue<decimal>(nameof(Thuvao), ref fThuvao, value); }
        }
        decimal fTong;
        public decimal Tong
        {
            get { return fTong; }
            set { SetPropertyValue<decimal>(nameof(Tong), ref fTong, value); }
        }
    }

}
