//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class Donhang : XPObject
    {
        short fMadonhang;
        public short Madonhang
        {
            get { return fMadonhang; }
            set { SetPropertyValue<short>(nameof(Madonhang), ref fMadonhang, value); }
        }
        DateTime fNgaydathang;
        public DateTime Ngaydathang
        {
            get { return fNgaydathang; }
            set { SetPropertyValue<DateTime>(nameof(Ngaydathang), ref fNgaydathang, value); }
        }
        Trangthai fTrangthai;
        [Association(@"DonhangReferencesTrangthai")]
        public Trangthai Trangthai
        {
            get { return fTrangthai; }
            set { SetPropertyValue<Trangthai>(nameof(Trangthai), ref fTrangthai, value); }
        }
        string fDiachi;
        public string Diachi
        {
            get { return fDiachi; }
            set { SetPropertyValue<string>(nameof(Diachi), ref fDiachi, value); }
        }
        Menu fMasanpham;
        [Association(@"DonhangReferencesMenu")]
        public Menu Masanpham
        {
            get { return fMasanpham; }
            set { SetPropertyValue<Menu>(nameof(Masanpham), ref fMasanpham, value); }
        }
        [Association(@"DonhangCTReferencesDonhang")]
        public XPCollection<DonhangCT> DonhangCTs { get { return GetCollection<DonhangCT>(nameof(DonhangCTs)); } }
        [Association(@"HoadonReferencesDonhang")]
        public XPCollection<Hoadon> Hoadons { get { return GetCollection<Hoadon>(nameof(Hoadons)); } }
    }

}
