//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class DonhangCT : XPObject
    {
        Donhang fMadonhang;
        [Association(@"DonhangCTReferencesDonhang")]
        public Donhang Madonhang
        {
            get { return fMadonhang; }
            set { SetPropertyValue<Donhang>(nameof(Madonhang), ref fMadonhang, value); }
        }
        string fSanpham;
        public string Sanpham
        {
            get { return fSanpham; }
            set { SetPropertyValue<string>(nameof(Sanpham), ref fSanpham, value); }
        }
        string fSoluong;
        public string Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<string>(nameof(Soluong), ref fSoluong, value); }
        }
    }

}
