//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class HoadonCT : XPObject
    {
        Hoadon fMaHDCT;
        [Association(@"HoadonCTReferencesHoadon")]
        public Hoadon MaHDCT
        {
            get { return fMaHDCT; }
            set { SetPropertyValue<Hoadon>(nameof(MaHDCT), ref fMaHDCT, value); }
        }
        string fTensanpham;
        public string Tensanpham
        {
            get { return fTensanpham; }
            set { SetPropertyValue<string>(nameof(Tensanpham), ref fTensanpham, value); }
        }
        short fSoluong;
        public short Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<short>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fGia;
        public decimal Gia
        {
            get { return fGia; }
            set { SetPropertyValue<decimal>(nameof(Gia), ref fGia, value); }
        }
        decimal fThanhtien;
        public decimal Thanhtien
        {
            get { return fThanhtien; }
            set { SetPropertyValue<decimal>(nameof(Thanhtien), ref fThanhtien, value); }
        }
    }

}
