//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class Khachhang : XPObject
    {
        string fTenkhachhang;
        public string Tenkhachhang
        {
            get { return fTenkhachhang; }
            set { SetPropertyValue<string>(nameof(Tenkhachhang), ref fTenkhachhang, value); }
        }
        string fSdtKhachhang;
        public string SdtKhachhang
        {
            get { return fSdtKhachhang; }
            set { SetPropertyValue<string>(nameof(SdtKhachhang), ref fSdtKhachhang, value); }
        }
        string fNgaysinh;
        public string Ngaysinh
        {
            get { return fNgaysinh; }
            set { SetPropertyValue<string>(nameof(Ngaysinh), ref fNgaysinh, value); }
        }
        [Association(@"ThanhtoanReferencesKhachhang")]
        public XPCollection<Thanhtoan> Thanhtoans { get { return GetCollection<Thanhtoan>(nameof(Thanhtoans)); } }
    }

}
