//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class Menu : XPObject
    {
        NhomSP fManhom;
        [Association(@"MenuReferencesNhomSP")]
        public NhomSP Manhom
        {
            get { return fManhom; }
            set { SetPropertyValue<NhomSP>(nameof(Manhom), ref fManhom, value); }
        }
        string fMasanpham;
        public string Masanpham
        {
            get { return fMasanpham; }
            set { SetPropertyValue<string>(nameof(Masanpham), ref fMasanpham, value); }
        }
        string fTensanpham;
        public string Tensanpham
        {
            get { return fTensanpham; }
            set { SetPropertyValue<string>(nameof(Tensanpham), ref fTensanpham, value); }
        }
        long fGiatien;
        public long Giatien
        {
            get { return fGiatien; }
            set { SetPropertyValue<long>(nameof(Giatien), ref fGiatien, value); }
        }
        short fSoluongconlai;
        public short Soluongconlai
        {
            get { return fSoluongconlai; }
            set { SetPropertyValue<short>(nameof(Soluongconlai), ref fSoluongconlai, value); }
        }
        [Association(@"DonhangReferencesMenu")]
        public XPCollection<Donhang> Donhangs { get { return GetCollection<Donhang>(nameof(Donhangs)); } }
    }

}
