//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class NhomSP : XPObject
    {
        string fManhom;
        public string Manhom
        {
            get { return fManhom; }
            set { SetPropertyValue<string>(nameof(Manhom), ref fManhom, value); }
        }
        string fTennhom;
        public string Tennhom
        {
            get { return fTennhom; }
            set { SetPropertyValue<string>(nameof(Tennhom), ref fTennhom, value); }
        }
        [Association(@"MenuReferencesNhomSP")]
        public XPCollection<Menu> Menus { get { return GetCollection<Menu>(nameof(Menus)); } }
    }

}
