//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class Taikhoan : XPObject
    {
        string fMataikhoan;
        public string Mataikhoan
        {
            get { return fMataikhoan; }
            set { SetPropertyValue<string>(nameof(Mataikhoan), ref fMataikhoan, value); }
        }
        string fTentaikhoan;
        public string Tentaikhoan
        {
            get { return fTentaikhoan; }
            set { SetPropertyValue<string>(nameof(Tentaikhoan), ref fTentaikhoan, value); }
        }
        string fMatkhau;
        public string Matkhau
        {
            get { return fMatkhau; }
            set { SetPropertyValue<string>(nameof(Matkhau), ref fMatkhau, value); }
        }
        string fHoten;
        public string Hoten
        {
            get { return fHoten; }
            set { SetPropertyValue<string>(nameof(Hoten), ref fHoten, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fSdt;
        public string Sdt
        {
            get { return fSdt; }
            set { SetPropertyValue<string>(nameof(Sdt), ref fSdt, value); }
        }
        string fDiachi;
        public string Diachi
        {
            get { return fDiachi; }
            set { SetPropertyValue<string>(nameof(Diachi), ref fDiachi, value); }
        }
        string fGioitinh;
        public string Gioitinh
        {
            get { return fGioitinh; }
            set { SetPropertyValue<string>(nameof(Gioitinh), ref fGioitinh, value); }
        }
        [Association(@"LuongReferencesTaikhoan")]
        public XPCollection<Luong> Luongs { get { return GetCollection<Luong>(nameof(Luongs)); } }
        [Association(@"ThanhtoanReferencesTaikhoan")]
        public XPCollection<Thanhtoan> Thanhtoans { get { return GetCollection<Thanhtoan>(nameof(Thanhtoans)); } }
        [Association(@"HoadonReferencesTaikhoan")]
        public XPCollection<Hoadon> Hoadons { get { return GetCollection<Hoadon>(nameof(Hoadons)); } }
    }

}
