//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace QLCF.Module.BusinessObjects.database
{
    [DefaultClassOptions]
    [NavigationItem]
    public partial class Thanhtoan : XPObject
    {
        string fMathanhtoan;
        public string Mathanhtoan
        {
            get { return fMathanhtoan; }
            set { SetPropertyValue<string>(nameof(Mathanhtoan), ref fMathanhtoan, value); }
        }
        decimal fSotien;
        public decimal Sotien
        {
            get { return fSotien; }
            set { SetPropertyValue<decimal>(nameof(Sotien), ref fSotien, value); }
        }
        string fTrangthaithanhtoan;
        public string Trangthaithanhtoan
        {
            get { return fTrangthaithanhtoan; }
            set { SetPropertyValue<string>(nameof(Trangthaithanhtoan), ref fTrangthaithanhtoan, value); }
        }
        Hoadon fMahoadon;
        [Association(@"ThanhtoanReferencesHoadon")]
        public Hoadon Mahoadon
        {
            get { return fMahoadon; }
            set { SetPropertyValue<Hoadon>(nameof(Mahoadon), ref fMahoadon, value); }
        }
        Taikhoan fMataikhoan;
        [Association(@"ThanhtoanReferencesTaikhoan")]
        public Taikhoan Mataikhoan
        {
            get { return fMataikhoan; }
            set { SetPropertyValue<Taikhoan>(nameof(Mataikhoan), ref fMataikhoan, value); }
        }
        Khachhang fSDTkhachhang;
        [Association(@"ThanhtoanReferencesKhachhang")]
        public Khachhang SDTkhachhang
        {
            get { return fSDTkhachhang; }
            set { SetPropertyValue<Khachhang>(nameof(SDTkhachhang), ref fSDTkhachhang, value); }
        }
    }

}
